name: Build Game (Windows and Linux)
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pgzero pgzhelper pyinstaller

    - name: Build with PyInstaller
      run: |
        # Для Windows используем ; для Linux :
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          pyinstaller --onefile --noconsole --name "Unpathetic-Hell" --add-data "images;images" main.py
        else
          pyinstaller --onefile --name "unpathetic-hell" --add-data "images:images" main.py
        fi
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Unpathetic-Hell-${{ matrix.os }}
        path: |
          dist/Unpathetic-Hell.exe
          dist/unpathetic-hell
